# Generated by Django 4.1.12 on 2025-03-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperInfo', '0002_paperinfo_keywords_paperinfo_paperpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='authors',
            field=models.CharField(max_length=1022),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='venue',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='venue_link',
            field=models.URLField(default=''),
        ),
    ]
