# Generated by Django 4.1.12 on 2023-11-20 04:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPapersCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=50)),
                ('papers', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'author_papers_cache',
            },
        ),
        migrations.CreateModel(
            name='PaperCitationsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=50)),
                ('citations', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'paper_citations_cache',
            },
        ),
        migrations.CreateModel(
            name='PaperDetailsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=50)),
                ('details', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'paper_details_cache',
            },
        ),
        migrations.CreateModel(
            name='PaperRecommendationsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=50)),
                ('recommendations', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'paper_recommendations_cache',
            },
        ),
        migrations.CreateModel(
            name='PaperReferencesCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=50)),
                ('references', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'paper_references_cache',
            },
        ),
    ]
